//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace PictureSharing.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ThreadingServices")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long GebruikerIDField;
        
        private string GebruikerNaamField;
        
        private string GebruikersPWField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long GebruikerID {
            get {
                return this.GebruikerIDField;
            }
            set {
                if ((this.GebruikerIDField.Equals(value) != true)) {
                    this.GebruikerIDField = value;
                    this.RaisePropertyChanged("GebruikerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GebruikerNaam {
            get {
                return this.GebruikerNaamField;
            }
            set {
                if ((object.ReferenceEquals(this.GebruikerNaamField, value) != true)) {
                    this.GebruikerNaamField = value;
                    this.RaisePropertyChanged("GebruikerNaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GebruikersPW {
            get {
                return this.GebruikersPWField;
            }
            set {
                if ((object.ReferenceEquals(this.GebruikersPWField, value) != true)) {
                    this.GebruikersPWField = value;
                    this.RaisePropertyChanged("GebruikersPW");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Foto", Namespace="http://schemas.datacontract.org/2004/07/ThreadingServices")]
    public partial class Foto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long FotoIDField;
        
        private string FotoNaamField;
        
        private long GebruikerIDField;
        
        private string PathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FotoID {
            get {
                return this.FotoIDField;
            }
            set {
                if ((this.FotoIDField.Equals(value) != true)) {
                    this.FotoIDField = value;
                    this.RaisePropertyChanged("FotoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FotoNaam {
            get {
                return this.FotoNaamField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoNaamField, value) != true)) {
                    this.FotoNaamField = value;
                    this.RaisePropertyChanged("FotoNaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long GebruikerID {
            get {
                return this.GebruikerIDField;
            }
            set {
                if ((this.GebruikerIDField.Equals(value) != true)) {
                    this.GebruikerIDField = value;
                    this.RaisePropertyChanged("GebruikerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGebruikersNaam", ReplyAction="http://tempuri.org/IService1/GetGebruikersNaamResponse")]
        System.Threading.Tasks.Task<string> GetGebruikersNaamAsync(long gebrID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGebruikersPW", ReplyAction="http://tempuri.org/IService1/GetGebruikersPWResponse")]
        System.Threading.Tasks.Task<string> GetGebruikersPWAsync(long gebrID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetGebruikersNaam", ReplyAction="http://tempuri.org/IService1/SetGebruikersNaamResponse")]
        System.Threading.Tasks.Task<bool> SetGebruikersNaamAsync(string gebruikersNaam, long gebrID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetGebruikersPW", ReplyAction="http://tempuri.org/IService1/SetGebruikersPWResponse")]
        System.Threading.Tasks.Task<bool> SetGebruikersPWAsync(string password, long gebrID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddGebruiker", ReplyAction="http://tempuri.org/IService1/AddGebruikerResponse")]
        System.Threading.Tasks.Task AddGebruikerAsync(PictureSharing.ServiceReference1.User gebruiker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGebruiker", ReplyAction="http://tempuri.org/IService1/GetGebruikerResponse")]
        System.Threading.Tasks.Task<PictureSharing.ServiceReference1.User> GetGebruikerAsync(long gebrID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllGebruikers", ReplyAction="http://tempuri.org/IService1/GetAllGebruikersResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<PictureSharing.ServiceReference1.User>> GetAllGebruikersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InlogMethode", ReplyAction="http://tempuri.org/IService1/InlogMethodeResponse")]
        System.Threading.Tasks.Task<PictureSharing.ServiceReference1.User> InlogMethodeAsync(string gebrNaam, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadFoto", ReplyAction="http://tempuri.org/IService1/UploadFotoResponse")]
        System.Threading.Tasks.Task UploadFotoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFotoNaam", ReplyAction="http://tempuri.org/IService1/GetFotoNaamResponse")]
        System.Threading.Tasks.Task<string> GetFotoNaamAsync(long fotoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFotoPath", ReplyAction="http://tempuri.org/IService1/GetFotoPathResponse")]
        System.Threading.Tasks.Task<string> GetFotoPathAsync(long fotoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFotos", ReplyAction="http://tempuri.org/IService1/GetAllFotosResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<PictureSharing.ServiceReference1.Foto>> GetAllFotosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetFotoPath", ReplyAction="http://tempuri.org/IService1/SetFotoPathResponse")]
        System.Threading.Tasks.Task<bool> SetFotoPathAsync(long fotoID, string fotoPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetFotoNaam", ReplyAction="http://tempuri.org/IService1/SetFotoNaamResponse")]
        System.Threading.Tasks.Task<bool> SetFotoNaamAsync(long fotoID, string fotoNaam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFoto", ReplyAction="http://tempuri.org/IService1/AddFotoResponse")]
        System.Threading.Tasks.Task AddFotoAsync(PictureSharing.ServiceReference1.Foto foto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGebruikerID", ReplyAction="http://tempuri.org/IService1/GetGebruikerIDResponse")]
        System.Threading.Tasks.Task<long> GetGebruikerIDAsync(long fotoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFotoByGebruiker", ReplyAction="http://tempuri.org/IService1/GetFotoByGebruikerResponse")]
        System.Threading.Tasks.Task<PictureSharing.ServiceReference1.Foto> GetFotoByGebruikerAsync(long gebrID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFoto", ReplyAction="http://tempuri.org/IService1/DeleteFotoResponse")]
        System.Threading.Tasks.Task DeleteFotoAsync(long fotoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFotosById", ReplyAction="http://tempuri.org/IService1/GetAllFotosByIdResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<PictureSharing.ServiceReference1.Foto>> GetAllFotosByIdAsync(long gebrId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PictureSharing.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PictureSharing.ServiceReference1.IService1>, PictureSharing.ServiceReference1.IService1 {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<string> GetGebruikersNaamAsync(long gebrID) {
            return base.Channel.GetGebruikersNaamAsync(gebrID);
        }
        
        public System.Threading.Tasks.Task<string> GetGebruikersPWAsync(long gebrID) {
            return base.Channel.GetGebruikersPWAsync(gebrID);
        }
        
        public System.Threading.Tasks.Task<bool> SetGebruikersNaamAsync(string gebruikersNaam, long gebrID) {
            return base.Channel.SetGebruikersNaamAsync(gebruikersNaam, gebrID);
        }
        
        public System.Threading.Tasks.Task<bool> SetGebruikersPWAsync(string password, long gebrID) {
            return base.Channel.SetGebruikersPWAsync(password, gebrID);
        }
        
        public System.Threading.Tasks.Task AddGebruikerAsync(PictureSharing.ServiceReference1.User gebruiker) {
            return base.Channel.AddGebruikerAsync(gebruiker);
        }
        
        public System.Threading.Tasks.Task<PictureSharing.ServiceReference1.User> GetGebruikerAsync(long gebrID) {
            return base.Channel.GetGebruikerAsync(gebrID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<PictureSharing.ServiceReference1.User>> GetAllGebruikersAsync() {
            return base.Channel.GetAllGebruikersAsync();
        }
        
        public System.Threading.Tasks.Task<PictureSharing.ServiceReference1.User> InlogMethodeAsync(string gebrNaam, string password) {
            return base.Channel.InlogMethodeAsync(gebrNaam, password);
        }
        
        public System.Threading.Tasks.Task UploadFotoAsync() {
            return base.Channel.UploadFotoAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetFotoNaamAsync(long fotoID) {
            return base.Channel.GetFotoNaamAsync(fotoID);
        }
        
        public System.Threading.Tasks.Task<string> GetFotoPathAsync(long fotoID) {
            return base.Channel.GetFotoPathAsync(fotoID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<PictureSharing.ServiceReference1.Foto>> GetAllFotosAsync() {
            return base.Channel.GetAllFotosAsync();
        }
        
        public System.Threading.Tasks.Task<bool> SetFotoPathAsync(long fotoID, string fotoPath) {
            return base.Channel.SetFotoPathAsync(fotoID, fotoPath);
        }
        
        public System.Threading.Tasks.Task<bool> SetFotoNaamAsync(long fotoID, string fotoNaam) {
            return base.Channel.SetFotoNaamAsync(fotoID, fotoNaam);
        }
        
        public System.Threading.Tasks.Task AddFotoAsync(PictureSharing.ServiceReference1.Foto foto) {
            return base.Channel.AddFotoAsync(foto);
        }
        
        public System.Threading.Tasks.Task<long> GetGebruikerIDAsync(long fotoID) {
            return base.Channel.GetGebruikerIDAsync(fotoID);
        }
        
        public System.Threading.Tasks.Task<PictureSharing.ServiceReference1.Foto> GetFotoByGebruikerAsync(long gebrID) {
            return base.Channel.GetFotoByGebruikerAsync(gebrID);
        }
        
        public System.Threading.Tasks.Task DeleteFotoAsync(long fotoID) {
            return base.Channel.DeleteFotoAsync(fotoID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<PictureSharing.ServiceReference1.Foto>> GetAllFotosByIdAsync(long gebrId) {
            return base.Channel.GetAllFotosByIdAsync(gebrId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:39046/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IService1,
        }
    }
}
