//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreadingServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public long PhotoId { get; set; }
        public string PhotoName { get; set; }
        public long UserId { get; set; }
        public string Path { get; set; }
        public byte[] ImageData { get; set; }
    }
}
